[package]
name = "extrack"
version = "0.1.0"
authors = ["Viktor Franzen <viktor@frnzn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
